'''
Given a profile matrix Profile, we can evaluate the probability of every k-mer in a string Text and find a Profile-most probable k-mer in Text, i.e., a k-mer that was most likely to have been generated by Profile among all k-mers in Text. For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT. Indeed, every other 12-mer in this string has probability 0.

In general, if there are multiple Profile-most probable k-mers in Text, then we select the first such k-mer occurring in Text.
Profile-most Probable k-mer Problem

Find a Profile-most probable k-mer in a string.

Given: A string Text, an integer k, and a 4 × k matrix Profile.

Return: A Profile-most probable k-mer in Text. (If multiple answers exist, you may return any one.)
Sample Dataset

ACCTGTTTATTGCCTAAGTTCCGAACAAACCCAATATAGCCCGAGGGCCT
5
0.2 0.2 0.3 0.2 0.3
0.4 0.3 0.1 0.5 0.1
0.3 0.3 0.5 0.2 0.4
0.1 0.2 0.1 0.1 0.2

Sample Output

CCGAG
'''

FILEPATH = r"BA2C_find_a_profile-most_probable_k-mer_in_a_string\data.txt"

LETTER_TO_INDEX = {"A": 1, "C": 2, "G": 3, "T": 4}

def kmer_to_probability(kmer, profile):
    probability = profile[LETTER_TO_INDEX[kmer[0]]][0]

    for i in range(len(kmer) - 1):
        second_letter = LETTER_TO_INDEX[kmer[i + 1]]
        probability *= profile[second_letter][i - 1]

    return probability

def main():
    with open(FILEPATH) as file:
        data = file.read().strip().split("\n")
    text = data[0]
    k = int(data[1])
    profile = [list(map(float, r.split())) for r in data[2:]]

    print(max([text[i:(i + k)] for i in range(len(text) - k + 1)], key=lambda kmer: kmer_to_probability(kmer, profile)))

if __name__ == "__main__":
    main()