'''
Problem

The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,… are generated by the following simple rule
Fn=⎧⎩⎨Fn-1+Fn-2,1,0,n>1,n=1,n=0.

Given: A positive integer n≤25.

Return: The value of Fn.

Source: Algorithms by Dasgupta, Papadimitriou, Vazirani. McGraw-Hill. 2006.
Sample Dataset

6

Sample Output

8
'''

FILEPATH = r"FIBO_fibonacci_numbers\data.txt"

def fibonacci(n, cache={}):
    if n in cache:
        return cache[n]
    
    if n == 1:
        return n
    
    cache[n] = fibonacci(n - 1) + fibonacci(n - 2)

    return cache[n]
     

def main():
    with open(FILEPATH) as file:
        n = int(file.read().strip())

    print(fibonacci(n))

if __name__ == "__main__":
    main()